### ISSUE TITLE
Not highlighting Liquid syntax

### ISSUE THREAD

**Issue by jsimplicio** [ForbesLindesay-Unmaintained/liquid-brackets#1]
I'm not sure how this extension should work on Brackets,
I have HTML files that have Liquid written all over it but it's not getting highlighted.

![screen shot 2014-09-03 at 11 14 57 am](https://cloud.githubusercontent.com/assets/7318958/4137273/79af6172-3385-11e4-9f00-1ee56be4a9eb.png)

**Comment by ForbesLindesay** [comment]
Does it have a `.liquid` file extension?  That would definitely be needed.  If they already have a `.liquid` file extension, try looking at it in a few different themes and see if it still fails to highlight them.

If that works, please close this issue. If not, let me know and I'll do further testing.

**Comment by jsimplicio** [comment]
It does not. It is HTML. I thought it would maybe work in files that are not Liquid.

Thanks, I will close the issue.
